'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace KLbirdPark

    Partial Public Class customer
        Public Property IdPayment As String
        Public Property name As String
        Public Property email As String
        Public Property contact As String
        Public Property address As String
        Public Property cardHolder As String
        Public Property nameCard As String
        Public Property IdOrder As String
    
        Public Overridable Property tblorder As tblorder
    
    End Class

End Namespace
