'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace KLbirdPark

    Partial Public Class tblorder
        Public Property IdOrder As String
        Public Property totalQtyAdult As String
        Public Property totalQtyChild As String
        Public Property totalAmountAdult As String
        Public Property totalAmountChildren As String
        Public Property totalAmount As String
    
        Public Overridable Property customers As ICollection(Of customer) = New HashSet(Of customer)
    
    End Class

End Namespace
